# Rust formatting configuration
# See: https://rust-lang.github.io/rustfmt/

# Fundamental settings
edition = "2021"
hard_tabs = false
tab_spaces = 4
max_width = 100
use_small_heuristics = "Default"

# Import settings
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
imports_layout = "Mixed"

# Function and closure settings
fn_single_line = false
fn_args_layout = "Tall"
where_single_line = true
force_explicit_abi = true

# Control flow settings
control_brace_style = "AlwaysNextLine"
brace_style = "SameLineWhere"

# Comment settings
comment_width = 80
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true

# String settings
format_strings = true

# Macro settings
format_macro_matchers = true
format_macro_bodies = true

# Item settings
reorder_impl_items = true
type_punctuation_density = "Wide"
space_before_colon = false
space_after_colon = true

# Trailing settings
trailing_comma = "Vertical"
trailing_semicolon = true

# Newline settings
newline_style = "Unix"
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0

# Match settings
match_block_trailing_comma = true
match_arm_blocks = true
match_arm_leading_pipes = "Never"

# Struct settings
struct_field_align_threshold = 0
struct_lit_single_line = true

# Array settings
array_width = 60
chain_width = 60

# Misc settings
use_try_shorthand = true
use_field_init_shorthand = true
condense_wildcard_suffixes = true
force_multiline_blocks = false
overflow_delimited_expr = false
space_around_ranges = false
spaces_around_ranges = false
binop_separator = "Front"
remove_nested_parens = true
combine_control_expr = true
short_array_element_width_threshold = 10
